-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 20:04:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Persona Cris
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Persona Cris
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Persona Cris` DEFAULT CHARACTER SET utf8 ;
USE `Persona Cris` ;

-- -----------------------------------------------------
-- Table `Persona Cris`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona Cris`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `sobre_mi` VARCHAR(150) NOT NULL,
  `profesion` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `url_foto` VARCHAR(80) NOT NULL,
  `url_portada` VARCHAR(80) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona Cris`.`tipo_empleo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona Cris`.`tipo_empleo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona Cris`.`experiencia_laboral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona Cris`.`experiencia_laboral` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `puesto` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  `fecha_final` VARCHAR(45) NULL,
  `url_foto` VARCHAR(45) NOT NULL,
  `Persona_id` INT NOT NULL,
  `tipo_empleo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`, `tipo_empleo_id`),
  INDEX `fk_experiencia_laboral_Persona_idx` (`Persona_id` ASC) VISIBLE,
  INDEX `fk_experiencia_laboral_tipo_empleo1_idx` (`tipo_empleo_id` ASC) VISIBLE,
  CONSTRAINT `fk_experiencia_laboral_Persona`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `Persona Cris`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_experiencia_laboral_tipo_empleo1`
    FOREIGN KEY (`tipo_empleo_id`)
    REFERENCES `Persona Cris`.`tipo_empleo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona Cris`.`tipo_habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona Cris`.`tipo_habilidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona Cris`.`habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona Cris`.`habilidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `porcentaje_de_dominio` INT NOT NULL,
  `Persona_id` INT NOT NULL,
  `tipo_habilidad_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`, `tipo_habilidad_id`),
  INDEX `fk_habilidades_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  INDEX `fk_habilidades_tipo_habilidad1_idx` (`tipo_habilidad_id` ASC) VISIBLE,
  CONSTRAINT `fk_habilidades_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `Persona Cris`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habilidades_tipo_habilidad1`
    FOREIGN KEY (`tipo_habilidad_id`)
    REFERENCES `Persona Cris`.`tipo_habilidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona Cris`.`proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona Cris`.`proyectos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(150) NOT NULL,
  `fecha_de_inicio` VARCHAR(45) NOT NULL,
  `fecha_de_fin` VARCHAR(45) NULL,
  `url_image` VARCHAR(80) NOT NULL,
  `url_proyecto` VARCHAR(80) NOT NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_proyectos_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectos_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `Persona Cris`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Persona Cris`.`educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Persona Cris`.`educacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `fecha_inicio` VARCHAR(45) NOT NULL,
  `fecha_final` VARCHAR(45) NULL,
  `url_logo_imagen` VARCHAR(80) NULL,
  `Persona_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Persona_id`),
  INDEX `fk_educacion_Persona1_idx` (`Persona_id` ASC) VISIBLE,
  CONSTRAINT `fk_educacion_Persona1`
    FOREIGN KEY (`Persona_id`)
    REFERENCES `Persona Cris`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
